#!  /bin/sh
# /etc/init.d/ubilling

########################################################################
######################## Конфигурация путей ############################

SHAPER="/etc/shaper.sh" #Путь к шейперу
SQL="/etc/init.d/mysql" # Путь до init.d скрипта MySQL
WEB="/etc/init.d/apache2" #  Путь до init.d скрипта Apache2
DHCP="/etc/init.d/isc-dhcp-server" # Путь до init.d скрипта Dhcp3-server
BAND="/etc/init.d/bandwidthd" # Путь до init.d скрипта Bandwindthd
STAR="/usr/sbin/stargazer" # Путь до bin файла stargazer
SOFTD="/etc/init.d/softflowd" #  Путь до init.d скрипта  Softflowd
FIREWALL="/etc/firewall.sh"
#Softflowd для разных подсетей


 case "$1" in
   start)
#Перезапускаем 
$SQL restart
#$WEB restart
#$DHCP restart
######################################################################################
# Добавляем наши адреса в NAT таблицу
$FIREWALL start
# Запускаем Bandwindthd
#$BAND start
#Запускаем softflowd
#$SOFTD start
# Запускаем HTB (Шейпер)
$SHAPER start
# Запускаем Stargazer
$STAR
     ;;


   stop)
#Убиваем все процессы старгазера
killall stargazer
#Удаляем правила шейпера
$SHAPER stop
#Останавливаем softflowd
$SOFTD stop

#Останавливаем Bandwindthd
$BAND stop


# Чистим правила в таблицах Iptables и удаляем списки IPSET
$FIREWALL stop


#Удаляем учётные записи с конфигурацией шейпера.
rm -rf /etc/stargazer/dn/*

     ;;
   *)
     echo "Usage: /etc/init.d/ubilling {start|stop}"
     exit 1
     ;;
 esac

 exit 0
